feat: Setup Slither
ubiquity/nft-rewards pull request #7
Opened 2024-02-15 17:15 UTC by gpylypchuk

Resolves [#3](https://github.com/ubiquity/nft-rewards/issues/3) issue.

2024-02-15 18:12 UTC, gpylypchuk commented
I'm ignoring the Slither warning because the actual contracts of OpenZeppelin are with ```pragma solidity ^0.8.20```

2024-02-15 19:13 UTC, pavlovcik commented on src/NftReward.sol
> +pragma solidity ^0.8.20;
This is really interesting

2024-02-16 08:37 UTC, rndquu requested changes

2024-02-16 08:37 UTC, rndquu commented on src/NftReward.sol
> +        require(_newMinter != address(0), "Minter cannot be zero address");
Pls add tests for all newly added `require()` statements

2024-02-16 20:15 UTC, gpylypchuk commented
should I add the merged changes to this PR?

2024-02-16 21:43 UTC, rndquu commented
> should I add the merged changes to this PR? (about #4)

Yes, you should merge the `development` branch because there are code conflicts which should be resolved

2024-02-17 01:08 UTC, gpylypchuk commented
Done @rndquu !

2024-02-19 11:51 UTC, rndquu requested changes
1. There is still this warning:
```
NftReward.safeMint(NftReward.MintRequest,bytes) (src/NftReward.sol#145-176) uses timestamp for comparisons
	Dangerous comparisons:
	- require(bool,string)(block.timestamp < _mintRequest.deadline,Signature expired) (src/NftReward.sol#155)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#block-timestamp
```

I think we can simply exclude the `block-timestamp` detector.

2. There is still this warning:
```
Pragma version^0.8.20 (src/NftReward.sol#2) necessitates a version too recent to be trusted. Consider deploying with 0.8.18.
solc-0.8.24 is not recommended for deployment
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity
```

What if we use solidity v0.8.18?

3. There is still this info warning:
```
Parameter NftReward.invalidateNonce(uint256)._nonceValue (src/NftReward.sol#223) is not in mixedCase
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#conformance-to-solidity-naming-conventions
```

Either exclude this detector either refactor the code.

4. Pls make sure the slither check workflow fails on any warning in the `NftReward.sol` contract

5. Pls update the slither worflow to run only when `*.sol` files are changed

2024-02-19 16:06 UTC, gpylypchuk commented
> 1. There is still this warning:
> 
> ```
> NftReward.safeMint(NftReward.MintRequest,bytes) (src/NftReward.sol#145-176) uses timestamp for comparisons
> 	Dangerous comparisons:
> 	- require(bool,string)(block.timestamp < _mintRequest.deadline,Signature expired) (src/NftReward.sol#155)
> Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#block-timestamp
> ```
> 
> I think we can simply exclude the `block-timestamp` detector.
> 
> 2. There is still this warning:
> 
> ```
> Pragma version^0.8.20 (src/NftReward.sol#2) necessitates a version too recent to be trusted. Consider deploying with 0.8.18.
> solc-0.8.24 is not recommended for deployment
> Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity
> ```
> 
> What if we use solidity v0.8.18?
> 
> 3. There is still this info warning:
> 
> ```
> Parameter NftReward.invalidateNonce(uint256)._nonceValue (src/NftReward.sol#223) is not in mixedCase
> Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#conformance-to-solidity-naming-conventions
> ```
> 
> Either exclude this detector either refactor the code.
> 
> 4. Pls make sure the slither check workflow fails on any warning in the `NftReward.sol` contract
> 5. Pls update the slither worflow to run only when `*.sol` files are changed

In 2, I tested before and there is still the warning because of the OZ libraries

2024-02-19 16:35 UTC, rndquu commented
> In 2, I tested before and there is still the warning because of the OZ libraries

But there is no warning for `NftReward.sol` in this case, right?

2024-02-19 16:57 UTC, gpylypchuk commented
> > In 2, I tested before and there is still the warning because of the OZ libraries
> 
> But there is no warning for `NftReward.sol` in this case, right?

correct!

2024-02-19 18:58 UTC, rndquu commented
> > > In 2, I tested before and there is still the warning because of the OZ libraries
> > 
> > 
> > But there is no warning for `NftReward.sol` in this case, right?
> 
> correct!

Then it makes sense to update `NftReward.sol` to use solidity `v0.8.18` since OZ contracts are not part of this project

2024-02-19 19:31 UTC, gpylypchuk commented on src/NftReward.sol
> +pragma solidity ^0.8.18;
@rndquu what do you think?

2024-02-19 19:36 UTC, rndquu commented on src/NftReward.sol
> +pragma solidity ^0.8.18;
Perhaps if https://github.com/crytic/slither-action targets only the https://github.com/ubiquity/nft-rewards/tree/development/src folder the OZ related warnings would be gone?

2024-02-19 19:38 UTC, gpylypchuk commented
Should we fail on medium or low? Also I think we should Ignore the OZ libraries 🤔

2024-02-19 19:39 UTC, gpylypchuk commented on src/NftReward.sol
> +pragma solidity ^0.8.18;
Yes I am thinking that

2024-02-19 19:43 UTC, rndquu commented
> Should we fail on medium or low? Also I think we should Ignore the OZ libraries 🤔

Yes, we use this strategy (fall on any slither warning or compiler warning) in our main repo https://github.com/ubiquity/ubiquity-dollar/

Not all of the slither detectors are included in our main repo because it makes sense to be reasonable (for example, `block.timestamp` related warnings can be excluded)

2024-02-19 20:03 UTC, gpylypchuk commented
> > Should we fail on medium or low? Also I think we should Ignore the OZ libraries 🤔
> 
> Yes, we use this strategy (fall on any slither warning or compiler warning) in our main repo https://github.com/ubiquity/ubiquity-dollar/
> 
> Not all of the slither detectors are included in our main repo because it makes sense to be reasonable (for example, `block.timestamp` related warnings can be excluded)

yep, I added a detector ignore about OZ libraries & timestamp

2024-02-19 20:06 UTC, gpylypchuk commented
@rndquu should I add this: ```"exclude_informational": true``` to ignore this ```solc-0.8.24 is not recommended for deployment
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity``` ?

2024-02-20 14:04 UTC, rndquu commented
> @rndquu should I add this: `"exclude_informational": true` to ignore this `solc-0.8.24 is not recommended for deployment Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity` ?

If we remove the [exclude_informational](https://github.com/ubiquity/nft-rewards/pull/7/files#diff-959713dbf93e19e462fad9058feb6086c9c053d875e23c9ffc637ac12c26ea52R4) config the slither workflow still passes, right?

2024-02-20 16:15 UTC, gpylypchuk commented
> > @rndquu should I add this: `"exclude_informational": true` to ignore this `solc-0.8.24 is not recommended for deployment Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity` ?
> 
> If we remove the [exclude_informational](https://github.com/ubiquity/nft-rewards/pull/7/files#diff-959713dbf93e19e462fad9058feb6086c9c053d875e23c9ffc637ac12c26ea52R4) config the slither workflow still passes, right?

No, I think that is because is like a low vuln.

2024-02-20 16:29 UTC, rndquu commented
> > > @rndquu should I add this: `"exclude_informational": true` to ignore this `solc-0.8.24 is not recommended for deployment Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity` ?
> > 
> > 
> > If we remove the [exclude_informational](https://github.com/ubiquity/nft-rewards/pull/7/files#diff-959713dbf93e19e462fad9058feb6086c9c053d875e23c9ffc637ac12c26ea52R4) config the slither workflow still passes, right?
> 
> No, I think that is because is like a low vuln. In [this](https://github.com/ubiquity/nft-rewards/pull/7/commits/0db9bf72729b4ff84b1813f7cbd0c0ed338dd11b) commit I removed the `exclude_informational` and the log show that failed because of that.

I don't understand from the log output, what file causes the `solc-0.8.24 is not recommended for deployment` error?

2024-02-20 16:44 UTC, gpylypchuk commented
> exclude_informational

That is because slither only recommends deployment with the version [0.8.18](https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity) and the OZ contracts are in  ^0.8.20 so there is no way to not recognize that error.

2024-02-20 16:47 UTC, gpylypchuk commented
I just added a line in ```foundry.toml``` about ```solc_version = "0.8.20"``` so you can select the version you want to compile.

2024-02-20 16:52 UTC, rndquu commented
> I just added a line in `foundry.toml` about `solc_version = "0.8.20"` so you can select the version you want to compile.

But that doesn't solve the warning as far as I understand

Overall we shouldn't exclude all low level issues. This is getting out of hand so lets:
1. Remove `exclude_informational: true`
2. Add the `solc-version` detector to exceptions. The only valid case I can think of is the usage of the `PUSH0` instruction which is mainly supported.

2024-02-20 17:05 UTC, gpylypchuk commented
> > I just added a line in `foundry.toml` about `solc_version = "0.8.20"` so you can select the version you want to compile.
> 
> But that doesn't solve the warning as far as I understand
> 
> Overall we shouldn't exclude all low level issues. This is getting out of hand so lets:
> 
> 1. Remove `exclude_informational: true`
> 2. Add the `solc-version` detector to exceptions. The only valid case I can think of is the usage of the `PUSH0` instruction which is mainly supported.

done!

2024-02-21 14:37 UTC, rndquu approved these changes

2024-02-21 16:03 UTC, gitcoindev approved these changes
Reviewed, read all comments and approving from my side, too!

2024-02-21 16:03 UTC, merged